version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - aspnetcoreapp-networks

  # postgres (service name) => name to use for the database connection in the aspnetcore project
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - aspnetcoreapp-networks

networks:
  aspnetcoreapp-networks:
    driver: bridge
